config/routes.rb
Rails.application.routes.draw do
  resources :seasons
  resources :statistics
  resources :players
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/lifetime_total.rb
class LifetimeTotal < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  has_one :lifetime_total

  has_many :statistics
end

app/models/player_season.rb
class PlayerSeason < ApplicationRecord
end

app/models/season.rb
class Season < ApplicationRecord
end

app/models/statistic.rb
class Statistic < ApplicationRecord
  belongs_to :player

end

app/models/team.rb
class Team < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.fetch(:player, {})
    end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: %i[ show edit update destroy ]

  # GET /seasons or /seasons.json
  def index
    @seasons = Season.all
  end

  # GET /seasons/1 or /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons or /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: "Season was successfully created." }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1 or /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: "Season was successfully updated." }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1 or /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: "Season was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def season_params
      params.fetch(:season, {})
    end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :set_statistic, only: %i[ show edit update destroy ]

  # GET /statistics or /statistics.json
  def index
    @statistics = Statistic.all
  end

  # GET /statistics/1 or /statistics/1.json
  def show
  end

  # GET /statistics/new
  def new
    @statistic = Statistic.new
  end

  # GET /statistics/1/edit
  def edit
  end

  # POST /statistics or /statistics.json
  def create
    @statistic = Statistic.new(statistic_params)

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, notice: "Statistic was successfully created." }
        format.json { render :show, status: :created, location: @statistic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statistics/1 or /statistics/1.json
  def update
    respond_to do |format|
      if @statistic.update(statistic_params)
        format.html { redirect_to @statistic, notice: "Statistic was successfully updated." }
        format.json { render :show, status: :ok, location: @statistic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1 or /statistics/1.json
  def destroy
    @statistic.destroy
    respond_to do |format|
      format.html { redirect_to statistics_url, notice: "Statistic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statistic
      @statistic = Statistic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def statistic_params
      params.fetch(:statistic, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nba</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/seasons/_form.html.erb
<%= form_with(model: season) do |form| %>
  <% if season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
        <% season.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Editing Season</h1>

<%= render 'form', season: @season %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

app/views/seasons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seasons</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seasons.each do |season| %>
      <tr>
        <td><%= link_to 'Show', season %></td>
        <td><%= link_to 'Edit', edit_season_path(season) %></td>
        <td><%= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Season', new_season_path %>

app/views/seasons/new.html.erb
<h1>New Season</h1>

<%= render 'form', season: @season %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_season_path(@season) %> |
<%= link_to 'Back', seasons_path %>

app/views/statistics/_form.html.erb
<%= form_with(model: statistic) do |form| %>
  <% if statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(statistic.errors.count, "error") %> prohibited this statistic from being saved:</h2>

      <ul>
        <% statistic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statistics/edit.html.erb
<h1>Editing Statistic</h1>

<%= render 'form', statistic: @statistic %>

<%= link_to 'Show', @statistic %> |
<%= link_to 'Back', statistics_path %>

app/views/statistics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statistics</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statistics.each do |statistic| %>
      <tr>
        <td><%= link_to 'Show', statistic %></td>
        <td><%= link_to 'Edit', edit_statistic_path(statistic) %></td>
        <td><%= link_to 'Destroy', statistic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Statistic', new_statistic_path %>

app/views/statistics/new.html.erb
<h1>New Statistic</h1>

<%= render 'form', statistic: @statistic %>

<%= link_to 'Back', statistics_path %>

app/views/statistics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_statistic_path(@statistic) %> |
<%= link_to 'Back', statistics_path %>